### ISSUE TITLE
Muliple elements from Book of Vile Darkness are missing

### ISSUE THREAD

**Issue by silasary** [CBLoader/CBParts#6]
https://code.google.com/archive/p/cbloader/issues/170

**Comment by Highborne13** [comment]
It seems all the Divine Boons from BoVD are missing:

Divine Boons:
The concept of Divine Boons has been a part of 4e as long as the alternative reward system has been a thing - they're powers granted by the gods to reward favors done or perhaps encourage an adventure to give faith to them. For this reason, you don't have to be an evil character to acquire any of these Divine Boons; the dark gods of the World Axis are perfectly willing and able to play the temptation game with heroic mortals. There's one Boon for each of the Evil or Chaotic Evil gods, each of which has a large paragraph of flavor text, and they consist of the following:
Asmodeus's Dread Authority: Once per encounter, you can make a Ranged 10 charm effect that allows you to slide the creature targeted 1 square/tier as a free action at the start of each of its turns until they pass a save. Once per day, you can also spend a minor action to force a creature under the effects of Dread Authority to either fall prone or take 5/tier fire damage.

Bane's Battle Acumen: Once per day, when you roll initiative, you can shift each ally within 5 squares of you 1 square/tier. Additionally, whenever you roll a natural 19+ on a weapon attack, one ally within 5 squares can shift 1 square as a free action - if you have the Paragon version of this boon, they can instead shift 2 squares, and if you have the Epic version, you can shift either 1 ally 2 squares or 2 allies 1 square.

Gruumsh's Bloodthirsty Wrath: Once per encounter, when you reduce an enemy to 0 HP, you gain temporary HP equal to this boon's level. Additionally, once per day, when bloodied, if you hit an enemy with a melee attack, you can then make a melee basic attack against a random adjacent creature and spend a healing surge.

Lolth's Fickle Favor: You gain a Resist 5/tier against poison an a +1/3/5 bonus to Stealth checks. Additionally, once per encounter, if you are bloodied, you can invoke this boon as an immediate reaction. Doing so lets you roll a d8; on an odd number, you are Dazed until the end of your next turn, and on an even number, you can teleport a number of squares equal to the result and then turn invisible until the end of your next turn.

Tharizdun's Madness Spiral: You gain a +2 bonus to saves against charm effect,s fear effects, and ongoing psychic damage. Also, once per encounter, you can reroll an attack roll, but if the second roll is 10 or less, then you are Stunned until the end of your next turn after resolving the effect.

Tiamat's Insatiable Greed: You gain a +1 to +6 bonus (depends on the value of the boon) to damage rolls against any creatrue that damaged you since the end of your last turn. Additionally, once per day, you can use a minor action to drain a daily magic item power from an ally within sight to restore the daily power of a magic item you're carrying of equal or lower level.

Torog's Inescapable Suffering: You gain a +1 bonus to attack rolls whilst bloodied. Once per day, when you hit a creature with a melee attack, you can inflict Immobilized and ongoing 5/tier Poison damage on all adjacent creatures to you.

Vecna's Dark Secret: You gain a +2/tier bonus to Knowledge checks, and once per day, you can inflict Vulnerable 5/tier Necrotic on an ally within 5 squares to gain Resist 10/15/20 Necrotic damage yourself as well as a +1d6/tier bonus Necrotic damage to Necrotic damage-inflicting attacks. The vulnerability, resistance and damage boost all last for the rest of the encounter.

Zehir's Shadow Cloak: So long as you have Total Concealment from a creature, you are treated as being Insubstantial when that creature attacks you. Additionally, once per encounter, you can inflict ongoing 5/tier Poison damage that ignores resistance as a bonus rider to a successful melee or ranged attack.

**Comment by thoth-process** [comment]
Everything from the Player's Book of the BoVD is present in the CB.  Everything from the DM's Book of the BoVD is not present in the CB, except for the Serpentine Knife of Zannad, which is present.  

Page references for missing material (including the above):
* Item - Magic Weapon - 1+ - Cursed Weapon (Cursed) (p.74)
* Item - Magic Weapon - 4+ - Berserk Weapon (Cursed) (p.74)
* Item - Magic Weapon - 12+ - Midnight Blade (p.78)
* Item - Magic Implement - 3+ - Obsidian Wand (p.78)
* Item - Magic Implement - 5+ - Skull of Terror (p.79)
* Item - Magic Implement - 7+ - Flesh-Eating Rod (p.77)
* Item - Arms - 9 - Bracers of Suffering (p.77)
* Item - Feet - 17 - Boots of Many Steps (Cursed) (p.74)
* Item - Neck - 5+ - Cloak of Poison (Cursed) (p.74)
* Item - Ring - 24 - Ring of Domination (p.79)
* Item - Waist - 12 - Girdle of Skulls (p.78)
* Item - Consumable - 5 - Potion of Delusion (Cursed) (p.75)
* Item - Artifact - Paragon - The Book of Vile Darkness (p.83)
* Item - Boon - 3+ - Asmodeus's Dread Authority (p.75)
* Item - Boon - 3+ - Bane's Battle Acumen (p.75)
* Item - Boon - 3+ - Gruumsh's Bloodthirsty Wrath (p.75)
* Item - Boon - 3+ - Lolth's Fickle Favor (p.76)
* Item - Boon - 12 - Tharizdun's Madness Spiral (p.76)
* Item - Boon - 5+ - Tiamat's Insatiable Greed (p.76)
* Item - Boon - 4+ - Torog's Inescapable Suffering (p.76)
* Item - Boon - 9+ - Vecna's Dark Secret (p.77)
* Item - Boon - 8+ - Zehir's Shadow Cloak (p.77)
